apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncwatt-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Team-DogFoot/dog-foot-k8s-manifests
    targetRevision: main
    path: apps/syncwatt/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: syncwatt-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
